//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudXam.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudXam.Locale.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arenza Corner, 319 Sector 17, Krishi Bazaar,Mumbai-400705.
        /// </summary>
        internal static string AddressAnkur {
            get {
                return ResourceManager.GetString("AddressAnkur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 386 ,Aswini Complex, Kalingarayan Street, Ram Nagar,Kanpur,UP-301214.
        /// </summary>
        internal static string AddressHema {
            get {
                return ResourceManager.GetString("AddressHema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 126 /2, Tulsiani Chambers, Yogakshema (nariman Point),Mumbai-405701.
        /// </summary>
        internal static string AddressManish {
            get {
                return ResourceManager.GetString("AddressManish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76 , Bharathi St, Chinnavedapatti, Ganapathy,Kochi,Kerala-201450.
        /// </summary>
        internal static string AddressSamir {
            get {
                return ResourceManager.GetString("AddressSamir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 199,Jawahar Nagar, Road No.3 , Gurgaon,New Delhi-203142.
        /// </summary>
        internal static string AddressTamanna {
            get {
                return ResourceManager.GetString("AddressTamanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your student record is not audited !! Kindly contact your class teacher before commencement of Ist semester(01 October 2020)..
        /// </summary>
        internal static string AlertTextIsAudited {
            get {
                return ResourceManager.GetString("AlertTextIsAudited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1A.
        /// </summary>
        internal static string Class1 {
            get {
                return ResourceManager.GetString("Class1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3C.
        /// </summary>
        internal static string Class3 {
            get {
                return ResourceManager.GetString("Class3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6A.
        /// </summary>
        internal static string Class6 {
            get {
                return ResourceManager.GetString("Class6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8B.
        /// </summary>
        internal static string Class8 {
            get {
                return ResourceManager.GetString("Class8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ankur@hotmail.com.
        /// </summary>
        internal static string EmailAnkur {
            get {
                return ResourceManager.GetString("EmailAnkur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hema@msn.com.
        /// </summary>
        internal static string EmailHema {
            get {
                return ResourceManager.GetString("EmailHema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manish@gmail.com.
        /// </summary>
        internal static string EmailManish {
            get {
                return ResourceManager.GetString("EmailManish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to samir@msn.com.
        /// </summary>
        internal static string EmailSamir {
            get {
                return ResourceManager.GetString("EmailSamir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tamanna@hotmail.com.
        /// </summary>
        internal static string EmailTamnna {
            get {
                return ResourceManager.GetString("EmailTamnna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..Please try again!!.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get student list.
        /// </summary>
        internal static string FetchStudentList {
            get {
                return ResourceManager.GetString("FetchStudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string GlobalOk {
            get {
                return ResourceManager.GetString("GlobalOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        internal static string LabeBirthDate {
            get {
                return ResourceManager.GetString("LabeBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        internal static string LabelEmailID {
            get {
                return ResourceManager.GetString("LabelEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string LabelGlobalSubmit {
            get {
                return ResourceManager.GetString("LabelGlobalSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Audited ?.
        /// </summary>
        internal static string LabelIsAudited {
            get {
                return ResourceManager.GetString("LabelIsAudited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LabelLogin {
            get {
                return ResourceManager.GetString("LabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin                              .
        /// </summary>
        internal static string LabelPin {
            get {
                return ResourceManager.GetString("LabelPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string LabelStudentClass {
            get {
                return ResourceManager.GetString("LabelStudentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string LabelStudentGender {
            get {
                return ResourceManager.GetString("LabelStudentGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students list for year 2019-20.
        /// </summary>
        internal static string LabelStudentList {
            get {
                return ResourceManager.GetString("LabelStudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        internal static string LabelStudentName {
            get {
                return ResourceManager.GetString("LabelStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll No.
        /// </summary>
        internal static string LabelStudentRollNo {
            get {
                return ResourceManager.GetString("LabelStudentRollNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string LabelUpdate {
            get {
                return ResourceManager.GetString("LabelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName                                 .
        /// </summary>
        internal static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your credentials.
        /// </summary>
        internal static string MessageCredentialsCheck {
            get {
                return ResourceManager.GetString("MessageCredentialsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Already Exists.
        /// </summary>
        internal static string MessageFileExists {
            get {
                return ResourceManager.GetString("MessageFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max files that can be added:.
        /// </summary>
        internal static string MessageMaxFileLimit {
            get {
                return ResourceManager.GetString("MessageMaxFileLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully!!.
        /// </summary>
        internal static string MessageRecordUpdate {
            get {
                return ResourceManager.GetString("MessageRecordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No student data found.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files attached.
        /// </summary>
        internal static string NoFileAttached {
            get {
                return ResourceManager.GetString("NoFileAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        internal static string NoFilePickedMessage {
            get {
                return ResourceManager.GetString("NoFilePickedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankur Thakkar.
        /// </summary>
        internal static string StudentAnkur {
            get {
                return ResourceManager.GetString("StudentAnkur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hema Pathak.
        /// </summary>
        internal static string StudentHema {
            get {
                return ResourceManager.GetString("StudentHema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manish Chandra.
        /// </summary>
        internal static string StudentManish {
            get {
                return ResourceManager.GetString("StudentManish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samir Mistry.
        /// </summary>
        internal static string StudentSamir {
            get {
                return ResourceManager.GetString("StudentSamir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanna Ghose.
        /// </summary>
        internal static string StudentTamanna {
            get {
                return ResourceManager.GetString("StudentTamanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Picker.
        /// </summary>
        internal static string TitleFilePicker {
            get {
                return ResourceManager.GetString("TitleFilePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
